/**
 * tunnel.js
 * Waits for local servers to be ready, then opens localtunnels for both
 * the Socket.IO backend (5000) and the React frontend (3000).
 * Writes the backend URL to .env.local so React uses it for socket connections.
 *
 * Usage:  npm run tunnel
 * Run AFTER starting server.js and react-scripts (npm start).
 */

const localtunnel = require('localtunnel');
const http = require('http');
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const ENV_FILE = path.join(ROOT, '.env.local');
const BYPASS_HEADERS = { 'bypass-tunnel-reminder': '1' };

// ── Helpers ────────────────────────────────────────────────────────────────

/** Poll a local port until it responds (max ~30 s). */
function waitForPort(port, timeout = 30000) {
  return new Promise((resolve, reject) => {
    const start = Date.now();
    const check = () => {
      const req = http.get(`http://localhost:${port}`, (res) => {
        res.destroy();
        resolve();
      });
      req.on('error', () => {
        if (Date.now() - start > timeout) {
          reject(new Error(`Port ${port} not ready after ${timeout / 1000}s`));
        } else {
          setTimeout(check, 1000);
        }
      });
      req.setTimeout(1000, () => req.destroy());
    };
    check();
  });
}

async function openTunnel(port, label) {
  process.stdout.write(`🚇  Opening ${label} tunnel (port ${port})… `);
  const tunnel = await localtunnel({ port });
  console.log(`✅  ${tunnel.url}`);
  tunnel.on('error', (err) => console.error(`\n⚠️  ${label} tunnel error:`, err.message));
  tunnel.on('close', () => console.log(`\n🔴  ${label} tunnel closed`));
  return tunnel;
}

// ── Main ───────────────────────────────────────────────────────────────────

async function main() {
  console.log('\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('  Video Call App — Tunnel Setup');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');

  // 1. Wait for both local servers to be ready
  console.log('⏳  Waiting for local servers to be ready…');
  try {
    await Promise.all([
      waitForPort(5000).then(() => console.log('   ✔ Socket.IO server (5000) is up')),
      waitForPort(3000).then(() => console.log('   ✔ React dev server  (3000) is up')),
    ]);
  } catch (err) {
    console.error('\n❌ ', err.message);
    console.error('   Make sure you ran: node server.js  AND  npm start');
    process.exit(1);
  }

  console.log();

  // 2. Backend tunnel first — need its URL before React starts reading env
  const backendTunnel = await openTunnel(5000, 'Backend (Socket.IO)');
  const socketUrl = backendTunnel.url;

  // 3. Write backend URL to .env.local
  const envContent = `# Auto-generated by scripts/tunnel.js\nREACT_APP_SOCKET_URL=${socketUrl}\n`;
  fs.writeFileSync(ENV_FILE, envContent);
  console.log(`📝  Written: REACT_APP_SOCKET_URL=${socketUrl}`);
  console.log('   ℹ️  Restart "npm start" to apply the new socket URL.\n');

  // 4. Frontend tunnel
  const frontendTunnel = await openTunnel(3000, 'Frontend  (React)');

  console.log('\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('  🎉  Share this link:');
  console.log(`      ${frontendTunnel.url}`);
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('\n  Tunnel password for visitors:');
  console.log('  https://loca.lt/mytunnelpassword');
  console.log('\nPress Ctrl+C to stop.\n');

  // 5. Graceful shutdown — also deletes .env.local
  process.on('SIGINT', () => {
    console.log('\nShutting down tunnels…');
    backendTunnel.close();
    frontendTunnel.close();
    try { fs.unlinkSync(ENV_FILE); } catch (_) {}
    console.log('🧹  .env.local removed. Bye!');
    process.exit(0);
  });
}

main().catch((err) => {
  console.error('\n❌  Unexpected error:', err.message);
  process.exit(1);
});
